<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Loja Seleto - Administração')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style_admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-fileupload.min.css')
                        ->prependStylesheet($this->basePath() . '/js/jcrop/css/jquery.Jcrop.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <script>var basePatch  = '<?=$this->basePath()?>'</script>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.produto.js')
        							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        							  ->prependFile($this->basePath() . '/js/jcrop/js/jquery.Jcrop.min.js')
        							  ->prependFile($this->basePath() . '/js/bootstrap-fileupload.min.js')
        							  ->prependFile($this->basepath() . '/js/jquery.maskedinput.min.js')
        							  ->prependFile($this->basepath() . '/js/jquery.price_format.1.8.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    	<div class="navbar navbar-inverse navbar-fixed-top">    		
		    <div class="navbar-inner">		    	
		        <div class="container">		        	
		          	<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		            	<span class="icon-bar"></span>
		            	<span class="icon-bar"></span>
		            	<span class="icon-bar"></span>
		          	</button>
		          	<a class="brand" href="<?=$this->basePath()?>">Loja Seleto</a>
		          	<div class="nav-collapse collapse">
		            	<ul class="nav">
		              		<li><a href="#">Home</a></li>
		              		<li><a href="<?php echo $this->url('admin-financeiro'); ?>">Financeiro</a></li>	
		              		<li><a href="<?php echo $this->url('admin-produto-categoria'); ?>">Categorias</a></li>		              		
		              		<li class="dropdown">
		              		    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
		              		        Produtos <b class="caret"></b>
		              		    </a>
		              		    <ul class="dropdown-menu">
		              		        <li><a href="<?php echo $this->url('admin-produto-home'); ?>">Geranciar Produtos</a></li>
		              		        <!-- <li><a href="<?php #echo $this->url('admin-produto-home/admin-produto-nutricional'); ?>">Gerenciar Tabela Nutricional</a></li> -->
                                </ul>
		              		</li>
		            	</ul>		            	
		            	<div class="btn-group pull-right">
							<a href="<?php print $this->url("Usuario/UsuarioAction",array("controller"=>"Login","action" => "logout"))?>"><button type="button" class="btn btn-primary">Sair</button></a>
						</div>
		          	</div><!--/.nav-collapse -->
		        </div>
		     </div>
    	</div>
    	
    	<div class="container">
    	
        	<?php echo $this->content; ?>
        	
        	<hr>
        	
        	<div class="row">
        	    <footer>
       			    <p>&copy; SpicyWeb 2013</p>
      		    </footer>
        	</div>
      		
    	</div> <!-- /container -->        
    </body>
</html>