
<div class="alert alert-info">
  <h4>Controle financeiro</h4>
      Neste local você encontra todas informações necessárias para gerar relatórios e analisar todo tráfego de vendas em sua <b>loja virtual</b>.
</div>


<h5>Ordens de Pagamento</h5>
<div class="btn-group">
  <button class="btn">Ordens Pendentes</button>
  <button class="btn">Pedidos Cancelados</button>
</div>
<br/>
<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Detalhe</strong> Você pode ver com detalhe quais produtos foram comprados em qualquer pedido processado clicando em cima do <B>N° Pedido</B>.
</div>
<table class="table">
              <thead>
                <tr>
                 <th></th>
                  <th width="50"><center>#ID</center></th>
                  <th><B>Referencia do Pedido Pagseguro</B></th>
                  <th>Data</th>
                  <th>Nome do Cliente</th>
                   <th><center>Forma de Pagamento</center></th>
                   <th>Total</th>
                   <th>Situação do pagamento</th>
                    <th width="110">Status do Envio</th>
                   
                </tr>
              </thead>
              <tbody>
              <?php
                  foreach($this->recibos AS $recibo)
                  {
                      
              ?>
                <tr class="<?php 
                        if($recibo->getSpagamento())
                        {
                            if(($recibo->getSpagamento()->getIdstatus()) == 7) print "error";
                            else if(($recibo->getSpagamento()->getIdstatus()) == 1) print "info";
                            else if(($recibo->getSpagamento()->getIdstatus()) == 3) print "success";
                        }
                        else {
                        	print "error";
                        }
                ?>">
                <td><input type="checkbox"/></td>
                <td><center><?=$recibo->getIdcontrolerecibo()?></center></td>
                  <td><a href="<?php print $this->url("admin-financeiro/admin-financeiro-action", array("idpedido" => $recibo->getIdcontrolerecibo()))?>"><?=$recibo->getNpedido()?></a></td>
                  <td>01/04/2012</td>
                  <td><?=$recibo->getUsuariousuarios()->getLogin()?></td>
                  <td><center><?
								 	if($recibo->getFpagamento())
								 	{
								 	    print $recibo->getFpagamento()->getTitulo();
								 	}
								 	else
								 	{
								 		print "Indisponível";
								 	}
								 	?></center></td>
                  <td><?=$recibo->getValor()?></td>
                  <td><center><B><?php 
							    if(!$recibo->getSpagamento())
							    {
							?>
								 Indisponível
								<?php 
							    }else {
                                ?>
                                    <?=$recibo->getSpagamento()->getTitulo()?>
                                <?							    	
							    }
								?></B></center></td>
                  <td><center><?php 
                      $status = $recibo->getStatus();
                  if(empty($status)) print "Indisponível"; 
                  else  print  "Concluído";
                  ?></center></td>
                </tr>
                <?php 
               
                  }
                ?>
              </tbody>
            </table>
            
            <p><i class="icon-warning-sign"></i> Altere o <b>status</b> do pedido clicando nos botões abaixo, lembre-se que a alteração de status só será possivel apos o sistema identificar o status "Atransação aceita".</p><br/>
            <div style="border: solid 1px black">
            <button type="button" class="btn btn-mini btn-primary"">Postado</button>
            <button type="button" class="btn btn-mini btn-info">Em Desenvolvimento</button>
            <button type="button" class="btn btn-mini btn-success">Enviado Para os Correios</button>
            <button type="button" class="btn btn-mini btn-danger">Cancelado</button>
            
            Aguardando confirmação de status Seleto
            </div>