<div class="alert">  
  <strong><h4>Gerenciamento de Produtos</h4></strong> <br/> Nessa sessão você pode gerenciar seus produtos como criar, editar e ou exluir de acordo com as suas necessidades.
</div>

<div class="row">
    <div class="span12">
        <ul class="breadcrumb">
          <li class="active"><i class="icon-gift"></i> Produto</li>
        </ul>
    </div>    
</div>

<div class="row">
    <div class="span8">
        <a class="btn" href="<?php echo $this->url('admin-produto-home/admin-default', array('action'=>'adicionar')); ?>" title="Novo Produto" style="float: left"><i class="icon-plus-sign"></i> Novo Produto</a> 
        
        <div class="btn-group" style="float: left; margin-left: 10px;">
            <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#">
                Buscar por Categoria
                <span class="caret"></span>
            </a>                    
            <ul class="dropdown-menu">
                <?php foreach($this->categorias as $categoria): ?>
                <li><a href="<?php echo $this->url('admin-produto-home/admin-categorias-default', array('action'=>'categorias', 'slug'=>$categoria->getSlug())); ?>"><?php echo $categoria->getNome(); ?></a></li>
                <?php endforeach; ?>                
            </ul>
        </div>        
        <div class="btn-group"  style="float:left; margin-left: 10px;">
            <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
                Buscar por Sub Categoria
                <span class="caret"></span>
            </a>                    
            <ul class="dropdown-menu">
                <?php 
                foreach($this->categorias as $categoria)
                {
                	foreach($categoria->getSubcategorias() as $subcategoria)
                	{
                    ?>
                    <li><a href="<?php echo $this->url('admin-produto-home/admin-categorias-default/admin-categorias-e-subcategoria', array('action'=>'categorias', 'slug'=>$categoria->getSlug(), 'slugSub'=>$subcategoria->getSlugSubcategoria())); ?>"><?php echo $subcategoria->getNome(); ?></a></li>
                    <?php
                	}
                }
                ?>                
            </ul>
        </div>       
    </div>    
    <div class="span4">
        <!-- <form class="form-search">
            <div class="input-append">
    		    <input type="text" class="input-medium search-query">
    		    <button type="submit" class="btn">Busca</button>
		    </div>
		</form> -->
    </div>
</div>

<table class="table table-striped table-bordered table-condensed">
	<caption>
		<h1>LISTA DE PRODUTOS DA LOJA SELETO</h1>
	</caption>
	<thead>
		<tr>
		    <th>ID</th>
			<th>Codigo do Produto</th>
			<th>Categoria</th>
			<th>Sub Categoria</th>
			<th>Titulo</th>
			<th>Valor</th>
			<th>Imagem</th>			
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
	    <?php foreach ($this->produto as $produto): ?>
	    <tr>
			<td><?php echo $produto->getIdproduto(); ?></td>
			<td><?php echo $produto->getCodigoProduto(); ?></td>
			<td><?php echo $produto->getProdutosubcategoria()->getCategorias()->getNome(); ?></td>
			<td><?php echo $produto->getProdutosubcategoria()->getNome(); ?></td>
			<td><?php echo $produto->getTitulo(); ?></td>
			<td><?php echo $produto->getValor(); ?></td>
			<td><img src="<?php echo $this->basePath()?>/images/produtos/thumb/<?php echo $produto->getFoto();?>" title="Imagem do Produto" alt="Imagem do Produto: <?php echo $produto->getIdproduto(); ?>" /></td>			
			<td width="150">				
				<a class="btn btn-small" href="<?php echo $this->url('admin-produto-home/admin-default', array('action'=>'editar', 'id'=>$produto->getIdproduto())); ?>" title="Editar Produto">
					<i class="icon-edit"></i> Editar
				</a>
				<a class="btn btn-small" href="<?php echo $this->url('admin-produto-home/admin-default', array('action'=>'excluir', 'id'=>$produto->getIdproduto())); ?>" onclick="return confirm('Confima a exclusão deste Produto?');" title="Excluir Produto">
					<i class="icon-remove"></i> Excluir
				</a>				
			</td>
		</tr>
	    <?php endforeach; ?>	
	</tbody>
</table>

<div class="pagination pagination-centered">	
	<?php echo $this->paginationControl($this->produto,'Sliding','paginator-produto',array('route' => '/page/')); ?>
</div>