<div class="alert alert-block">
  <h4>Gerenciamento dos Itens que compõe a Tabela Nutricional</h4>
  Nessa sessão você pode gerenciar seus itens que compõe a tabela de nutrição de acordo com suas necessidades.
</div>

<div class="row" style="margin-top: 50px;">
    <?php 
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin-produto-home/admin-produto-nutricional/admin-produto-nutricional-gerenciar',array('action'=>'editarItem','id'=>$this->idNutricionalNome)));
    $form->prepare();
    echo $this->form()->openTag($form);
        echo $this->formrow($form->get('id'));
    ?>
        <div class="control-group">
            <label class="control-label" for="nome">Nome</label>
            <div class="controls">
              <?php echo $this->formRow($form->get('nome')); ?>
            </div>
        </div>              
        <div class="control-group">
            <div class="controls">
              <a href="<?php echo $this->url('admin-produto-home/admin-produto-nutricional'); ?>" class="btn">Voltar</a>          
              <button class="btn btn-warning" type="submit">Alterar</button>
            </div>
        </div>        
    <?php echo $this->form()->closeTag(); ?>
</div>