<div class="alert alert-block">
  <h4>Gerenciamento de Tabelas Nutricionais</h4>
     Nessa sessão você pode gerenciar suas tabelas de nutrição de acordo com suas necessidades.
</div>

<div class="btn-toolbar" style="margin: 0;">

    <div class="btn-group">
      <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">
          Gerenciar Itens
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a class="my-accordion-toggle" href="#itens">Listar Itens</a></li>
        <li><a href="#myModalItens" role="button" data-toggle="modal">Adicionar Itens</a></li>
      </ul>
    </div>
    
    <div class="btn-group">
      <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
          Gerenciar Tabela Nutricional
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a class="my-accordion-toggle" href="#tabelas">Listar Tabela</a></li>
        <li><a href="#myModalTable" role="button" data-toggle="modal">Criar Tabela</a></li>
      </ul>
    </div>

</div>

<div class="container" style="margin-top: 20px;">
    <div class="row" id="itens">
        <div class="span12">
            <table class="table table-striped table-hover">
                <caption><h5>Gerenciando Itens</h5></caption>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Item Nome</th>                        
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->itens as $item): ?>
                    <tr>
                        <td><?php echo $item->getIdnutricionalNomes(); ?></td>
                        <td><?php echo $item->getNome(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('admin-produto-home/admin-produto-nutricional/admin-produto-nutricional-gerenciar',array('action'=>'editarItem','id'=>$item->getIdnutricionalNomes())); ?>" class="label"><i class="icon-edit"></i> Editar</a>
                            <a href="<?php echo $this->url('admin-produto-home/admin-produto-nutricional/admin-produto-nutricional-gerenciar',array('action'=>'excluirItem','id'=>$item->getIdnutricionalNomes())); ?>" class="label" onclick="return confirm('Confima a exclusão do Item?');"><i class="icon-remove"></i> Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="row" id="tabelas">
        <div class="span12">
            <table class="table table-striped table-hover">
                <caption><h5>Gerenciando itens da tabela</h5></caption>
                <thead>
                    <tr>
                        <th>#</th>                        
                        <th>Produto</th>
                        <th>Item</th>
                        <th>Quantidade</th>
                        <th>Valor Diário</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->tableNutricional as $table): ?>
                        <tr class="<?php echo $this->cores[$table->getProdutoproduto()->getIdproduto()]; ?>">
                            <td><?php echo $table->getIdprodutoNutricional(); ?></td>
                            <td><?php echo $table->getProdutoproduto()->getTitulo();?></td>
                            <td><?php echo $table->getProdutonutricionalNomes()->getNome(); ?></td>
                            <td><?php echo $table->getQuantidade(); ?></td>
                            <td><?php echo $table->getVd(); ?></td>                            
                            <td><a href="<?php echo $this->url('admin-produto-home/admin-produto-nutricional/admin-produto-nutricional-gerenciar',array('action'=>'editarTabelaNutricional','id'=>$table->getIdprodutoNutricional())); ?>" class="label"><i class="icon-edit"></i> Editar</a></td>
                            <td><a href="<?php echo $this->url('admin-produto-home/admin-produto-nutricional/admin-produto-nutricional-gerenciar',array('action'=>'excluirTabelaNutricional','id'=>$table->getIdprodutoNutricional())); ?>" class="label" onclick="return confirm('Confima a exclusão da linha da Tabela Nutricional?');"><i class="icon-remove"></i>  Excluir</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <p class="lead" style="margin-left: 40px;">Itens cadastrados</p>
        <ul class="nav nav-list tree">
          <?php foreach ($this->itens as $item): ?>
          <li style="float: left; margin-left: 20px;">
              <label class="tree-toggler nav-header">
                  <a href="#"><i class="icon-th"></i><?php echo $item->getNome(); ?></a>
              </label>
          </li>
          <?php endforeach; ?>
        </ul>
    </div>
</div>

<!-- Modal -->
<div id="myModalItens" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Adicionar Item Nutricional</h3>
    </div>
    <div class="modal-body">
        <div class="alert" id="mensagensItens">
            <button type="button" class="close" data-dismiss="alert">&times;</button>            
        </div>
        <p>
            <label class="control-label" for="nome">Nome:</label>
            <input type="text" id="nome" placeholder="Nome do Item" name="item">
        </p>           
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="addItems" class="btn btn-primary">Adcionar</button>
    </div>
</div>

<div id="myModalTable" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width: 952px;left: 42%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Adicionar Tabela Nutricional</h3>
    </div>
    <div class="modal-body">
        <div class="alert" id="mensagensTables">
            <button type="button" class="close" data-dismiss="alert">&times;</button>            
        </div>
        <!-- <p>
            <?php 
            #$form = $this->form;
            #$form->setAttribute('action', '#');
            #$form->prepare();
            #echo $this->form()->openTag($form);
            ?>              
              <div class="control-group">
                <label class="control-label" for="idproduto">Produtos</label>
                <div class="controls">
                  <?php #echo $this->formRow($form->get('idproduto')); ?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="idnutricionalNomes">Itens</label>
                <div class="controls">
                  <?php #echo $this->formRow($form->get('idnutricionalNomes')); ?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="quantidade">Quantidade</label>
                <div class="controls">
                  <?php #echo $this->formRow($form->get('quantidade')); ?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label" for="vd">Valor diário</label>
                <div class="controls">
                  <?php #echo $this->formRow($form->get('vd')); ?>
                </div>
              </div>
            <?php #echo $this->form()->closeTag(); ?>
        </p> -->
        
        <?php 
        $form = $this->form;
        $form->setAttribute('action', '#');
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="row line0" id="line-form">
            <?php 
                echo $this->formRow($form->get('idproduto'));
                echo $this->formRow($form->get('idnutricionalNomes'));
                echo $this->formRow($form->get('quantidade'));
                echo $this->formRow($form->get('vd'));
            ?>
        </div>
        <!-- <div class="row line1" id="line-form">
            <?php 
                echo $this->formRow($form->get('produtos'));
                echo $this->formRow($form->get('idnutricionalNomes'));
                echo $this->formRow($form->get('quantidade'));
                echo $this->formRow($form->get('vd'));
            ?>
        </div>
        <div class="row line2" id="line-form">
            <?php 
                echo $this->formRow($form->get('produtos'));
                echo $this->formRow($form->get('idnutricionalNomes'));
                echo $this->formRow($form->get('quantidade'));
                echo $this->formRow($form->get('vd'));
            ?>
        </div>
        <div class="row line3" id="line-form">
            <?php 
                echo $this->formRow($form->get('produtos'));
                echo $this->formRow($form->get('idnutricionalNomes'));
                echo $this->formRow($form->get('quantidade'));
                echo $this->formRow($form->get('vd'));
            ?>
        </div>
        <div class="row line4" id="line-form">
            <?php 
                echo $this->formRow($form->get('produtos'));
                echo $this->formRow($form->get('idnutricionalNomes'));
                echo $this->formRow($form->get('quantidade'));
                echo $this->formRow($form->get('vd'));
            ?>
        </div> -->
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
        <button id="addLinha" class="btn btn-info">Adicionar linha</button>
        <button id="addTableNutricional" class="btn btn-primary">Adcionar</button>
    </div>
</div>