<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ?>
        <script>var basePatch  = '<?=$this->basePath()?>'</script>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/usuario.js')
                                      ->prependFile($this->basePath() . '/js/painel.js')
                                      ->prependFile($this->basePath() . '/js/publico.js')
                                      ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>


    <!--[if IE 9]>
      <link href="<?=$this->basePath()?>/css/style-ie.css" rel="stylesheet" type="text/css">      
    <![endif]-->


    <!--[if !IE]><!--><script>
    if (/*@cc_on!@*/false) {
        document.documentElement.className+='ie10';
    }
    </script><!--<![endif]-->

    </head>
    <body>

          <div id="header">
            <div id="ContenTopoHeader">
              <div id="mn_topo">
                  <ul class="mn_topo">
				            <li class="Menu_topo">Olá <?=$this->infoUser->getLogin()?>, seja bem vindo a Loja Seleto</li>
				             <li class="Menu_topo"><a href="<?php print $this->url("Usuario/UsuarioAction",array("controller"=>"Login","action" => "logout"))?>">Sair</a></li>
                      <li class="Menu_topo" ><a href="">Acompanhe seus pedidos</a></li>
                      <li class="Menu_topo" style="background:none;">
                      <a href="<?=$this->url("publico-duvidas")?>">Dúvidas frequentes</a></li>
			            </ul>
               </div>      
              <a href="#" class="actionOpenCarrinho">
                <span class="Cesta" alt="Minha Cesta" title="Minha Cesta"><br/>
                  
                  <div id="Box_Visor_Qtd" style="<?if(count($this->carrinhoLista['listaAtual']) != 0) print "display:block"; else print "display:none";?>">  
                   <span class="Visor_Qtd"><?if(count($this->carrinhoLista['listaAtual']) != 0) print count($this->carrinhoLista['listaAtual']);?></span>
                  </div>

                  <p class="mc">MINHA CESTA</p>
                   <p class="valor_total"><?=$this->carrinhoLista['valorTotal']?></p>
                  <img class="dt_cesta" src="<?=$this->basePath()?>/images/dt_cesta.png">
                  </span>
              </a>
          </div>



               <div id="BoxCestaForm">
                <div id="box_compras" style="display:none;">
                  <?
                    print  $this->partial("layout/carrinho",array("carrinhoLista" => $this->carrinhoLista));
                  ?>
                
                  </div>
              </div>
          </div>
        
     
      <!--LOGIN -->

         <div id="Login_Cadastro" style="display:none">


            <div id="btn_form">
               <a href="" class="status_entrar" alt="login" title="Login">entrar</a>
               <a href="" class="status_criar_conta" alt="Criar conta" title="Criar conta">criar conta</a>
               <a href="" class="status_fechar"alt="fechar" title="Fechar">fechar</a>
           </div>
           <div id="form_login">     
              <form action="" class="formActionLogin">
                   <label class="status_login">Login:</label><br/><input type="text" class="login" value="Digite seu Login"><br/>
                   <label class="status_password">Senha:</label><br/><input type="password" class="Password" value="criar senha"><br/>
                   <a href="" class="esqueceuSenha">Esqueceu sua senha?</a><br/>
                   <input type="submit" value="Entrar" class="Eventlogin"><br/><br/><br/>
                   <p class="criar_conta">Ainda não tem uma conta?<a href="" class="criar_conta"> criar uma conta</a></p>
              </form>

            
           </div>

          <div id="form_cadastro" style="display:none">
             <form action="" class="formActionCadastro">
                  <label class="status_email">*E-mail:</label><br/><input type="text" class="email" value="digite aqui o seu e-mail"><br/>
                  <label class="status_login">*Login:</label><br/><input type="text" class="login" value="criar nome de usuário"><br/>
                  <label class="status_password">*Senha:</label><br/><input type="password" class="Password" value="criar senha"><br/>
                  <label class="status_password">*Confirmar senha:</label><br/><input type="password" class="Password" value="criar senha"><br/><br/>
                 <input type="submit" value="cadastrar" class="Eventcadastrar"><br/><br/><br/>
            </form>
         </div>
        </div>


        <!--ERRO-->
        <div id="form_erro" style="display:none">
          <div id="BoxFormErro">
                <div class="modelNotificacao">
                   <p class="atencaoErro"><!-- Titulo Box --></p>
                   <p class="erro"><!-- Lista de mensagens --></p>
                   <span class="tipo_erro"></span>
                   <br/>
                   <a href="" class="tentarNovamente"><!-- Titulo Botão --></a>
                </div> 
          </div>
        </div>
          
          <!--*****************************CONTEUDO*****************************-->

<div id="geral">

 <!--*****************************CONTEUDO TOPO*****************************-->
  <div id="topo_menu">
    <div id="menu_central">
      <a href="<?=$this->basePath()?>" title="SELETO ALIMENTOS"><h1 class="logo_seleto" title="Seleto Alimentos">SELETO ALIMENTOS</h1></a>
            
          <div id="box_menu">
            <img class="phone"src="<?=$this->basePath()?>/images/phone.png">
            <p class="txt_phone">Televendas: 55 11 3611-3143 / 3611-3179</p>
            <form action="<?php echo $this->url('publico-busca-produto'); ?>" method="get">            
                <input placeholder="buscar produto" class="search_topo" id="search" name="p">
                <input type="submit" value="Pesquisar" class="lupa_topo">
            </form>

                    <ul class="Menu">                    
                      <li class="lista_menu_cafe"><!--Cafés-->
                          <h3><a href="#">Cafes</a></h3>
                          
                          <ul class="dropdownCafe">
                              <li class="tt_dropdown">
                                  <a class="tt_dropdown" href="#">O Café Seleto tem um sabor <span class="ttd_dropdown"> delicioso</span></a>
                              </li>
                              <li class="imgDropdown">
                                  <img class="dom_menu" src="<?=$this->basePath()?>/images/dom_menu.png">
                              </li>
                              <li class="BoxAllFood">
                                  <ul>
                                      <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown">Café em pó</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/tipo-vacuo">Tipo vácuo</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/tipo-almofada">Tipo almofada</a></li>
                                      <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/cafe-em-po">Veja Mais</a></li>
                                      
                                      <li class="txtD_dropdown"><a class="txtD_dropdown" href="#">Café em cápsulas</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas/seleto-dom/cafe-seleto-em-capsula-levissimo">Seleto Dom Levissimo</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas/seleto-dom/cafe-seleto-em-capsula-intenso">Seleto Dom Intenso</a></li>
                                      <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas">Veja Mais</a></li>
                                      <li class="txtD_dropdown"><a class="txtD_dropdown" href="#">Descartáveis para casa</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/filtro-de-papel">Filtro de papel</a></li>
                                      <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/filtro-de-papel">Veja Mais</a></li>
                                  </ul>
                              </li> 
                          </ul>
                      </li>
                      
                      <li class="lista_menu_alimentos"><!--Alimentos-->
                        <h3><a href="#">Alimentos</a></h3>
                          
                          <ul class="dropdownAlimento" style="min-height:300px;">
                            <li class="tt_dropdown">
                              <a class="tt_dropdown" href="#">Seleto alimentos, seu café da manhã  <span class="ttd_dropdown"> completo</span>
                              </a>
                            </li>

                               <li class="imgDropdown">
                                <img class="BonecoSeleto" src="<?=$this->basePath()?>/images/BonecoSeleto.png">
                               </li>

                               <li class="BoxAllFood">
                                  <ul>
                                     <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown">Mistura para bolo</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo/mistura-para-bolo-de-chocolate-400g">Mistura para bolo de chocolate</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo/mistura-para-bolo-de-coco-400g">Mistura para bolo de coco</a></li>
                                     <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo">Veja Mais</a></li>
                                     <li class="txtD_dropdown"><a class="txtD_dropdown">Achocolatados em pó</a></li>  
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po/achocolatado-seleto-pote-400g">Achocolatado pote</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po/achocolatado-seleto-sache-400g">Achocolatado sache</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po/preparo-de-morango-400g">Preparo de morango em pó</a></li>
                                     <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po">Veja Mais</a></li>
                                  </ul> 
                              </li>
                          </ul>
                      </li>

                      <li class="lista_menu_produtos"><!--Todos Produtos-->
                        <h3><a href="#">Todos Produtos</a></h3>
                          <ul class="dropdownProduto">
                            <li class="tt_dropdown">
                              <a class="tt_dropdown" href="#">Veja todos os produtos,<span class="ttd_dropdown"> Seleto</span>
                              </a>
                            </li>
                                <!--Coluna 1-->
                             <li class="BoxAllFood">
                                  <ul>
                                     <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown">Mistura para bolo</a></li>

                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo/mistura-para-bolo-de-chocolate-400g">Mistura para bolo de chocolate</a></li>

                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo/mistura-para-bolo-de-coco-400g">Mistura para bolo de coco</a></li>

                                     <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/alimentos/mistura-para-bolo">Veja Mais</a></li>
                                     <li class="txtD_dropdown"><a class="txtD_dropdown">Descartáveis para casa</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="">Filtro de papel</a></li>
                                     <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="">Veja Mais</a></li>
                                  </ul> 
                              </li>
                                 <!--Coluna 2-->
                               <li class="BoxAllFood">
                                  <ul>
                                    <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown">Achocolatados em pó</a></li>  
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po/achocolatado-seleto-pote-400g">Achocolatado pote</a></li>
                                     <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po/achocolatado-seleto-sache-400g">Achocolatado sache</a></li>
                                     <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/alimentos/achocolatados-em-po">Veja Mais</a></li>
                                    <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown">Café em pó</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/tipo-vacuo">Tipo vácuo</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-po/tipo-almofada">Tipo almofada</a></li>
                                      <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/cafe-em-po">Veja Mais</a></li>
                                  </ul> 
                               </li>
                                  <!--Coluna 3-->
                               <li class="BoxAllFood">
                                  <ul>
                                    <li class="txtD_dropdown" style="margin-top:10px"><a class="txtD_dropdown" href="#">Café em cápsulas</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas/seleto-dom/cafe-seleto-em-capsula-levissimo">Seleto Dom Levissimo</a></li>
                                      <li class="txt_dropdown"><a class="txt_dropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas/seleto-dom/cafe-seleto-em-capsula-intenso">Seleto Dom Intenso</a></li>
                                      <li class="VejaMaisDropdown"><a class="VejaMaisDropdown" href="<?=$this->basePath()?>/produto/cafe-em-capsulas">Veja Mais</a></li>
                                  </ul> 
                              </li>
                          </ul>
                      </li>
                    
                </ul>
          </div>
    </div>

  </div>


	<!--****************BANNER PAGAMENTO/ENTREGAS/REDES SOCIAIS****************-->
                <div id="banner_informativo">
                  <div id="box_banner_informativo">
                    <h6 class="banner_pagamento">Pagamentos Pelo PagSeguro</h6>
                    <h6 class="banner_entrega">Entregas Via Sedex</h6>
                    <h6 class="banner_redes"><!--Redes Sociais Curta a Página Seleto No Facebook-->
                      <div id="banner_face">
                        <div id="fb-root"></div>
                          <script>(function(d, s, id) {
                          var js, fjs = d.getElementsByTagName(s)[0];
                          if (d.getElementById(id)) return;
                          js = d.createElement(s); js.id = id;
                          js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
                          fjs.parentNode.insertBefore(js, fjs);
                          }(document, 'script', 'facebook-jssdk'));</script>
                          <div class="fb-like" data-href="https://www.facebook.com/SeletoAlimentos?ref=ts&amp;fref=ts" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="false" data-send="false"></div>
                      </div>
                    </h6>
                  </div>
                </div>
    <!--****************FIM DO BANNER PAGAMENTO/ENTREGAS/REDES SOCIAIS****************-->

<!--*****************************CAMINHO SITE***************************-->
                	<?
                    print  $this->partial("layout/caminho",array("caminhoDefines" => $this->caminhoDefines));
                  ?>

<!--***************************** FIM DO CAMINHO SITE***************************-->
                	

<div id="conteudo_principal">

               
                <!--*********************FIM DO MENU LATERAL*********************-->
                
        <?php echo $this->content; ?>
        
                <!--*********************FIM DO MENU LATERAL PUBLICIDADE********************-->

          </div>

</div>

        
     <!--*******************FOOTER************************-->

<div id="footer">

    <div id="box_search_footer">
        <div class="search_footer">
            <form action="<?php echo $this->url('publico-busca-produto'); ?>" method="get">
              <input placeholder="buscar produto" class="search_footer" id="search_footer" name="p">
              <input type="submit" value="pesquisar" class="lupa_footer" title="Buscar Produto">
            </form>
        </div>
    </div>

    <div id="box_newsletter_footer">
      <div class="newsletter_footer">
           <p class="newsletter_footer">RECEBA DESCONTOS E OFERTAS EXCLUSIVAS</p>
           <input placeholder="Digite seu nome" class="news_footer"/>
           <input placeholder="Digite seu e-mail" class="news_footer"/>
           <input type="submit" class="ok_footer" value="OK" title="Receba descontos e ofertas exclusivas"/>
        </div>
    </div>

    <div id="box_menu_footer">
      <div class="menu_footer">
          <ul class="mn_footer">
             <li>INSTITUCIONAL</li>
                 <ul class="submenu">
                    <li><a href="" title="Quem Somos">Quem Somos</a></li>
                    <li><a href="" title="Mapa do Site">Mapa do Site</a></li>
                    <li><a href="" title="Fale Conosco">Fale Conosco</a></li>
                 </ul>
          </ul>

        <ul class="mn_footer">
          <li>DÚVIDAS FREQUENTES</li>
            <ul class="submenu">
               <li><a href="" title="Termos de Pesquisa">Perguntas Frequentes</a></li>
               <li><a href="" title="Meus Pedidos">Meus Pedidos</a></li>
               <li><a href="" title="Trocas e Devoluções">Trocas e Devoluções</a></li>
                <li><a href="" title="Editar Cadastro">Editar Cadastro</a></li>
                <li><a href="" title="Política de Privacidade">Política de Privacidade</a></li>
            </ul>
        </ul>

        <ul class="mn_footer">
          <li>ENTREGAS</li>
          <img src="<?=$this->basePath()?>/images/icon_sedex.png" alt="sedex" title="Entrega via Sedex"/>
        </ul>

        <ul class="mn_footer">
          <li>REDES SOCIAIS</li>
            <ul class="submenu">  
               <p class="text_redes_sociais">Acompanhe o Café Seleto <br/> nas redes sociais:</p>      
               <li><a href="https://www.facebook.com/SeletoAlimentos?ref=ts&fref=ts" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/facebook.png" alt="facebook" title="Facebook"/></a></li>
               <li><a href="https://twitter.com/seletoalimentos" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/twitter.png" alt="twitter" title="Twitter"/></a></li>
               <li><a href="http://instagram.com/seletoalimentos#" target="_blank" class="redes_sociais"><img src="<?=$this->basePath()?>/images/instagran.png" alt="instagran" title="Instagran"/></a></li>
            </ul>
        </ul>

      </div>
    </div>

    <div id="box_pagamento_footer">
      <div class="pagamento_footer">
          <p class="pagamentos">Formas de pagamento:</p>
          <a href=""><img src="<?=$this->basePath()?>/images/pagseguro.png" alt="Faça seu pagamento pelo PagSeguro" title="Faça seu pagamento pelo PagSeguro" /></a>
       </div>

    </div>

    <div id="box_direitosReservados_footer">
      <div class="direitosReservados_footer">
          <p class="direitos_reservados">© 2013 seleto. Todos os Direitos Reservados.</p>
        </div>
    </div>

</div>

<!--************************FIM DO FOOTER****************************-->
        

    </body>
</html>
        