<?php
$urlPattern = $_SERVER['REQUEST_URI'];
/*$formatUrl = function ($page) use ($urlPattern) {
            if (!preg_match('/page/', $urlPattern))                
                return $urlPattern . "/page/" . $page;                
            else
                return preg_replace('/\d/', $page, $urlPattern);
        };*/
$formatUrl = function ($page) use ($urlPattern) {
	if (!preg_match($this->route, $urlPattern))
		return $urlPattern . $this->route . $page;
	else
		return preg_replace('/\d/', $page, $urlPattern);
};
?>
<?php if ($this->pageCount): ?>
    
    <ul>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
        <li>
            <a href="<?php echo $formatUrl($this->previous) ?>">Anterior</a>
        </li>
    <?php else: ?>
        <li class="disabled">
            <a href="#">Anterior</a>
        </li>
    <?php endif; ?>

    
    <?php foreach ($this->pagesInRange as $item): ?>    
        <?php if($this->current == $item): ?>
        <li class="active">
            <a href="#"><?php echo $item;?></a>
        </li>
        <?php else: ?>
        <li>
            <a href="<?php echo $formatUrl($item) ?>"><?php echo $item;?></a>
        </li>        
        <?php endif;?>
    <?php endforeach;?>        

    
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <li>
            <a href="<?php echo $formatUrl($this->next); ?>">Próximo</a>
        </li>
    <?php else: ?>
        <li class="disabled">
            <a href="#">Próximo</a>
        </li>
    <?php endif; ?>
    </ul>
    
<?php endif; ?>