
<!--Institucional-->

				<div id="Institucional">
					<div id="MenuInstitucional">
						<ul id="nav" class="BoxMenuInstitucional">
							<li class="BoxMenuInstitucional" id="tab1">
								<a href="#duvida1" class="QuemSomos" title="Quem Somos">Quem Somos</a>
							</li>
							<li class="BoxMenuInstitucional" id="tab2">
								<a href="#duvida2" class="MapaSite" title="Mapa do Site">Mapa do Site</a>
							</li>
							<li class="BoxMenuInstitucional" id="tab3">
								<a href="#duvida3" class="PerguntasFrequentes" title="Perguntas Frequentes" >Perguntas Frequentes</a>
							</li>
							<li class="BoxMenuInstitucional" id="tab4">
								<a href="#duvida4" class="TrocasDevolucoes" title="Trocas e Devoluções" >Trocas e Devoluções</a>
							</li>
							<li class="BoxMenuInstitucional" id="tab5">
								<a href="#duvida5" class="PoliticaPrivacidade" title="Política de Privacidade" >Política de Privacidade</a>
							</li>
							<li class="BoxMenuInstitucional" id="tab6">
								<a href="#duvida6" class="FaleConosco" title="Fale Conosco" >Fale Conosco</a>
							</li>		
						</ul>
					</div>

					<div id="duvida"></div>
					
					<div id="conteudo_tabs">
										
    					<div id="duvida1" class="QuemSomos tab">
    						<div id="BoxInstitucional">
    							<h3 class="tt_Institucional">Quem somos</h3>
    							<p class="txt_Institucional">O Café Seleto é uma das marcas de café mais famosas e queridas do Brasil. Também pudera. Além de ter um sabor todo especial, sempre contou com memoráveis campanhas publicitárias, e possui o jingle mais conhecido da história da propaganda brasileira. E esta grande marca está de volta ao mercado com força total. Comprada pelo Grupo Mex, o Café Seleto está de cara nova e trazendo muitas novidades também. As embalagens estão mais modernas, a campanha publicitária renovada e o café, ainda mais saboroso.</p>
    
    							<h5 class="Sub_tt">Missão</h5>
    
    							<p class="txt_Institucional">Produzir e fornecer produtos de qualidade, inovadores, competitivos e sustentáveis em um ambiente socialmente responsável.</p>
    
    							<h5 class="Sub_tt">Visão</h5>
    
    							<p class="txt_Institucional">Ser uma das mais conceituadas e competitivas empresas alimentícias da América do Sul, reconhecida pelas práticas de qualidade, sustentabilidade e inovação.</p>
    						</div>
    					</div>
    					
    					<div id="duvida2" class="MapaSite tab">
    						<div id="BoxInstitucional">
    							<h3 class="tt_Institucional">Mapa Site</h3>
    						</div>	
    					</div>
    
    					<div id="duvida3" class="PerguntasFrequentes tab">
    					    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath();?>/js/jquery-ui-1.10.3/themes/base/jquery-ui.css">
                            <script type="text/javascript" src="<?php echo $this->basePath();?>/js/jquery-ui-1.10.3/ui/jquery.ui.accordion.js"></script>
                            <script type="text/javascript">
                            $(function(){
                                $("#accordion").accordion({heightStyle: "content"});
                            });
                            </script>
    						<div id="BoxInstitucional">
    							<h3 class="tt_Institucional">Perguntas Frequentes</h3>
    							<div id="accordion">
    								  <h3 class="TituloAccordion">Como faço para comprar os produtos Seleto pela internet?</h3>
    								  <div id="BoxAccordion">
    								    <p class="TextoAccordion">
    								    (Esse tutorial é construído pela agência conforme layout)
    								    </p>
    								  </div>
    								  <h3 class="TituloAccordion">Qual prazo de entrega dos meus pedidos?</h3>
    								  <div id="BoxAccordion">
    								    <p class="TextoAccordion">
    								    O prazo de entrega deve ser considerado a partir da aprovação do cadastro PAGSeguro.</p>
                                        <p class="SubTituloAccordion" style="text-decoration: underline">CAPITAIS DOS SEGUINTES ESTADOS:</p>
                                        <p class="SubTituloAccordion">- SP, DF* e PR: <span class="DetalheTxtAccordion">até 2 dias úteis.</span></p>    
                                        <p class="SubTituloAccordion">- RJ: <span class="DetalheTxtAccordion">até 3 dias úteis.</span></p>
                                        <p class="SubTituloAccordion">- AC*, AL*, AM, AP*, BA*, CE*, ES*, GO*, MA*, MG, MS*, MT*, PA*, PB*, PE*, PI*, RN*, RO*,</br> RS, RR*, SE*, SC e TO*: <span class="DetalheTxtAccordion">até 8 dias úteis.</span></p>
                                        <p class="SubTituloAccordion" style="text-decoration: underline">PARA AS DEMAIS CIDADES:</p>
                                        <p class="TextoAccordion">- Acrescentar 2 dias úteis aos prazos citados</p>
    								    </p>
    								  </div>

    								  <h3 class="TituloAccordion">Como posso acompanhar a entrega do meu pedido?</h3>
    								  <div id="BoxAccordion">
    								    <p class="TextoAccordion">
    								    É possível rastrear a entrega de seu pedido On-line através de nosso site.</p>
                                        <p class="TextoAccordion">(Segue sugestão mas tem que ver se atende a arquitetura da loja feita pela Spicy)</p>
                                        <p class="TextoAccordion">Caso não seja possível rastrear seu pedido desta forma, não hesite em nos contatar através do <span class="DetalheTxtAccordion">SAC</span> pelo telefone (11) 3611-3869 de segunda a sexta-feira das 8:00 as 12:30 e das 13:30 as 17h ou via <span class="DetalheTxtAccordion">site </span><a href="#" style="text-decoration: underline"> www.seletoalimentos.com.br</a>
    								    </p>
    								  </div>

    								  <h3 class="TituloAccordion">Como verificar ou cancelar um pedido?</h3>
    								  <div id="BoxAccordion">
    								    <p class="TextoAccordion">
    								    Para garantir nossos prazos de entrega de acordo com cada região, nosso Centro de Distribuição processa, prepara e envia os pedidos o mais rápido possível. Assim, não podemos garantir modificações ou cancelamentos após a finalização do pedido.</p>
                                        <p class="TextoAccordion">Para qualquer alteração no pedido (Ex: itens solicitados, endereço de entrega) pedimos à gentileza que contate conosco através do SAC (11) 3611-3869.
    								    </p>
    								  </div>


    								  <h3 class="TituloAccordion">Quanto rende um pacote de café?</h3>
    								  <div id="BoxAccordion">
    								    <p class="TextoAccordion">
    								    Proporção de café pode ser assim:</p> 

                                        <span class="DetalheTxtAccordion">Para café expresso:</span>
                                        <p class="TextoAccordion">1 kg de café expresso produz 142 cafés de 50 ml, considerando 07 gramas por xícara (1.000 gramas: 07 gramas = 142 xícaras). Portanto, 1 kg de café expresso produz 7,1 litros de café expresso (50 ml x 142 xícaras = 7,1 litros).</p> 

                                        <span class="DetalheTxtAccordion">Para café coado:</span> 
                                        <p class="TextoAccordion">1 kg de café moído produz 200 xícaras de café coado, considerando 05 gramas por xícara (1.000 gramas: 05 gramas = 200 xícaras). Portanto 1 kg de café moído produz 10,0 litros de café coado (50 ml x 200 xícaras = 10,0 litros).</p>  

                                        <span class="DetalheTxtAccordion">Café solúve:</span> 
                                        <p class="TextoAccordion">500 g produzem 50 xícaras de 50 ml doses aproximadamente.</p>  

                                        <span class="DetalheTxtAccordion" style="text-decoration: underline">DICA:</span></br> 

                                        <span class="DetalheTxtAccordion">O SEGREDO DA CONSERVAÇÃO</span></br> 
                                        <p class="TextoAccordion">Tão importante como o cuidado na hora de escolher e comprar café, a boa conservação do produto em casa é fundamental para assegurar uma degustação prazerosa. A razão é simples: o café se deteriora com facilidade e os efeitos decorrentes influenciam diretamente o aroma e o sabor da bebida. Fruto complexo, sua composição química o torna passível de várias transformações ao longo das diferentes fases de processamento. A torra dos grãos aciona uma cadeia de reações químicas que determinam o aroma e o sabor marcantes do café. Mas, depois de torrado, o produto envelhece rapidamente se não for embalado e conservado adequadamente. Para ter uma ideia da dimensão da complexidade do café, os especialistas afirmam que basta apenas um grão imperfeito para que o resultado seja percebido na xícara - são necessários cerca de 50 a 55 grãos para extrair uma dose de expresso.</p> 
                                        <p class="TextoAccordion">O primeiro segredo é adquirir quantidades menores de café, para que seu consumo seja rápido ou em tempo suficiente para evitar sua degradação depois de aberto. Isso porque o contato com o ar provoca sua oxidação. Em pouco tempo, perdem-se os aromas, e o café adquire gosto rançoso. Esse sabor já é significativo após duas semanas de exposição ao oxigênio. Assim, o pacote de 250 gramas mostra-se mais acertado, mas o de 500 gramas também pode servir. Depende do número de pessoas ou do volume 
                                        de consumo O tipo de embalagem é outro item importante para a preservação. Empacotado a vácuo, significa que o ar no interior do pacote foi extraído, evitando que o pó de café ali contido oxide. Fechado, o produto tem vida de prateleira de um ano.</p> 
                                        <p class="TextoAccordion">Depois de aberto, vale seguir algumas recomendações, a fim de minimizar os efeitos da oxidação. Manter o café na própria embalagem, O tipo de embalagem é outro item importante para a preservação. Empacotado a vácuo, significa que o ar no interior do pacote foi extraído, evitando que o pó de café ali contido oxide. Fechado, o produto tem vida de prateleira de um ano. O ideal, entretanto, seria comprar o café em grão e moê-lo em casa no momento do preparo, já que o pó perde aroma muito mais rápido. Os invólucros laminados valvulados funcionam bem para esse caso, pois permitem a saída de gases (basicamente o gás carbônico), liberados pelo grão nos cinco dias após a torra.</p> 
                                        <p class="TextoAccordion">Depois de aberto, vale seguir algumas recomendações, a fim de minimizar os efeitos da oxidação. Manter o café na própria embalagem, bem fechada, à temperatura ambiente, sempre longe da umidade e do calor, é aconselhável para quem for consumi-lo dentro de quatro ou cinco dias. O livro Café: um Guia do Apreciador (Editora Saraiva, São Paulo, 2005) dá preferência aos recipientes com vedação de borracha na tampa. Também adverte para não reutilizá-los, pois o café absorve com facilidade o aroma e o sabor de outros produtos. Se for consumido em mais de uma semana, convém mantê-lo sob-refrigeração. Nesse caso, porém, será melhor tirá-lo da geladeira um pouco antes do preparo e deixá-lo à temperatura ambiente para suavizar o choque térmico entre a água quente e o pó frio. Acima de 15 dias, convém guardá-lo no freezer (o café não congela!).</p> 

                                        <span class="DetalheTxtAccordion">O QUE É UM BLEND?</span></br> 
                                        <p class="TextoAccordion">Um blend de café é uma composição de grãos diferentes. Assim como os vinhos tem o seu assemblage ou corte, os grãos de café podem ser misturados para obter o máximo de variedade e qualidade na xícara. Essa mistura pode ser feita entre diferentes tipos de grão ou entre cafés de regiões do mundo todo. O blend é, portanto, uma miscelânea e não uma composição de partes homogêneas.</p> 
                                       
                                        <span class="DetalheTxtAccordion">Caso não encontre sua pergunta, por favor clique aqui para contatar a Seleto Alimentos diretamente atarvés do nosso site</span></br> <a href="#" style="text-decoration: underline"> www.seletoalimentos.com.br/sac</a> 

    								    </p>
    								  </div>

                                      <h3 class="TituloAccordion">Esqueci minha senha, como faço para acessar minha conta?</h3>
                                      <div id="BoxAccordion">
                                        <p class="TextoAccordion">(Segue sugestão mas tem que ver se atende a arquitetura da loja feita pela Spicy)</p>
                                      </div>
    							</div>

    						</div>
    					</div>
    
    					<div id="duvida4" class="TrocasDevolucoes tab">
    						<div id="BoxInstitucional">
    							<h3 class="tt_Institucional">Política de trocas e devolução<br/>Seleto Alimentos</h3>
    							<p class="txt_Institucional">Visando garantir total satisfação de nossos clientes e consumidores nossa política de trocas e devoluções está de acordo com o código de defesa do consumidor, preservando todos os seus direitos.</p>
    							<p class="txt_Institucional">Portanto toda e qualquer ocorrência ou divergência, seja uma embalagem violada, produto avariado ou um pedido que chegou diferente do solicitado, recuse o recebimento e contate-nos imediatamente. Caso já tenha recebido o produto e necessite fazer uma troca ou devolução é indispensável à apresentação da nota fiscal (que foi entregue junto com o produto). Também solicitamos a embalagem original, na qual o produto foi entregue.</p>
    							<p class="txt_Institucional">A troca de produtos defeituosos devem seguir as mesmas condições descritas na devolução por arrependimento/desistência. O frete do retorno de produtos defeituosos será de responsabilidade do Seleto Alimentos.</p>
    							<p class="txt_Institucional">O contato conosco pode ser feito pelo e-mail <a class="LinkTrocasDevolucoes" href="">sac.seletoalimentos@grupomex.com.br</a> ou pelo telefone <strong>(11) 3611-3869</strong>. Nosso horário de atendimento por telefone é de segunda a sexta-feira das 8:30 as 12:30h e das 13:30 as17h.</p> 
    							<p class="txt_Institucional">Enviaremos os melhores esforços para que tudo seja resolvido o mais rápido possível.</p>
    						</div>
    					</div>
    
    					<div id="duvida5" class="PoliticaPrivacidade tab">
    						<div id="BoxInstitucional">
    							<h3 class="tt_Institucional">Politica Privacidade</h3>
    							<h5 class="Sub_tt">Objetivo</h5>
    							<p class="txt_Institucional">Nossa Política de privacidade tem como objetivo definir e evidenciar nosso compromisso em garantir a proteção das informações coletadas dos usuários. Esses dados são importantes porque nos ajudam a tornar este site melhor e cada vez mais direcionado a você, usuário.</p>
    							<h5 class="Sub_tt">Compromisso de confidencialidade</h5>
    							<p class="txt_Institucional">Todas as informações dos usuários do site, inclusive seu e-mail, não serão fornecidas para terceiros (salvo situação da limitação legal, conforme item a seguir). As informações de pagamento e comercialização fornecidas por você serão mantidas em sigilo e utilizadas exclusivamente pelo Café Canecão.</p>
    							<h5 class="Sub_tt">Limitação legal do compromisso de confidencialidade</h5>
    							<p class="txt_Institucional">As informações fornecidas pelos usuários poderão ser entregues às autoridades estabelecidas se por estas forem solicitados para condução de investigação criminal ou apuração de crimes de qualquer natureza em que o usuário figure como réu ou investigado.</p>
    							<h5 class="Sub_tt">Manuseio das informações</h5>
    							<p class="txt_Institucional">Todos os dados pessoais informados ao nosso site são armazenados em um banco de dados reservado e com acesso restrito. Os funcionários da Seleto Alimentos habilitados que tiverem acesso a esses dados para o exercício de suas atividades profissionais são obrigados, por contrato, a manter a confidencialidade das informações e são terminantemente proibidos de utilizá-los indevidamente.</p>
    							<h5 class="Sub_tt">Responsabilidade comercial</h5>
    							<p class="txt_Institucional">A Loja Seleto Alimentos é responsável pelos produtos que vende e que se obriga(m) a cumprir as exigências da lei, inclusive no que se refere à proteção aos direitos do consumidor. Exija sempre a nota fiscal. Antes de usufruir de nossos serviços leia atentamente nosso Termo de Uso. Caso não esteja de acordo, por favor, não os utilize.</p>
    							<h5 class="Sub_tt">E-mail marketing</h5>
    							<p class="txt_Institucional">Nossas campanhas de e-mail marketing respeitam a política anti-spam e nossos informativos permitem o descadastramento de seu e-mail. Nesses e-mails não serão solicitadas confirmação de dados, cadastro e alteração/confirmação de senha. Também não serão enviados arquivos (executáveis ou não) anexados.</p>
    							<h5 class="Sub_tt">Segurança</h5>
    							<p class="txt_Institucional">O sistema de vendas do site foi planejado para garantir a privacidade das informações relativas a cartão de crédito, nome, residência, correio eletrônico e qualquer outra informação que o cliente tenha fornecido.</p>
    						</div>
    
    					</div>
    
    					<div id="duvida6" class="FaleConosco tab">
    						<div id="BoxInstitucional" style="width:250px; float:left;">
    							<h3 class="tt_Institucional">Fale conosco</h3>
    							<p class="txt_Institucional">Dúvidas, sugestões ou reclamações.</p><br/>
    				              <form class="FormInstitucional" action="">
    				                   <label class="tt_FormInstitucional">Nome:</label><br/>
    				                   <input type="text" class="NomeFormInst" value=""><br/>
    				                   <label class="tt_FormInstitucional">E-mail:</label><br/>
    				                   <input type="text" class="EmailFormInst" value=""><br/>
    				                   <label class="tt_FormInstitucional">Telefone:</label><br/>
    				                   <input type="text" class="TelefoneFormInst" value=""><br/>
    				                   <label class="tt_FormInstitucional">Destinatário:</label><br/>
    				                   <select class="DestinatarioFormInst">
                                       <option>Selecione</option>
                                       </select><br/>
    				                   <label class="tt_FormInstitucional">Mensagem:</label><br/>
    				                   <textarea class="AreaFormInstitucional" name="mensagem"></textarea><br/>
    				                   <input type="reset" value="Limpar" class="LimparFormInst">	
    				                   <input type="submit" value="Enviar" class="EnviarFormInst">
    				              </form>
    						</div>
                            <div id="BoxInstitucional" style="width:380px; float:left;">
                                <h3 class="tt_Institucional">Sac</h3>
                                <p class="txt_Institucional"style= "font-size:16px;" > Telefone (11) 3611-3867 de segunda à sexta-feira das 8:00h às 12:30h e das 13:30h às 17h </p><br/>
                            </div>
					    </div>
				    
				    </div>
				    
				</div>
				<!--Fim Institucional-->