<div id="conteudo_central">
    	<div id="box_detalhe">
    	
    		<!--<h3 class="Nome_detalhe"><?=$this->detalheProduto->getTitulo()?></h3>-->

    		<div id="galeria_detalhe">
            <!-- <div class="zoomWrapper" style="height:274px;width:411px;"> -->
               <div id="zoom_galeria" >
                    <center>
					    <img id="zoom_03" class="fotos_galeria"  data-zoom-image="<?=$this->basePath()?>/images/produtos/large/<?=$this->detalheProduto->getFoto();?>" src="<?=$this->basePath()?>/images/produtos/small/<?=$this->detalheProduto->getFoto();?>">
				    </center>
				<!-- </div> -->
                </div>
				<div id="gallery_01" style="width:212px;float:left; margin-top:20px;">					
					<a class="elevatezoom-gallery" data-zoom-image="<?=$this->basePath()?>/images/produtos/large/<?=$this->detalheProduto->getFoto();?>" data-image="<?=$this->basePath()?>/images/produtos/small/<?=$this->detalheProduto->getFoto();?>" href="tester">
						<img  src="<?=$this->basePath()?>/images/produtos/thumb/<?=$this->detalheProduto->getFoto();?>" class="thumb_produtos">
					</a>
					<?php foreach ($this->detalheProduto->getImagens() as $imagem): ?>
					    <a class="elevatezoom-gallery" data-zoom-image="<?=$this->basePath()?>/images/produtos/large/<?=$imagem->getImages();?>" data-image="<?=$this->basePath()?>/images/produtos/small/<?=$imagem->getImages();?>" href="#">
						    <img  src="<?=$this->basePath()?>/images/produtos/thumb/<?=$imagem->getImages();?>" class="thumb_produtos">
					    </a>
					<?php endforeach; ?>
				</div>
			</div>



			<div id="comprar_detalhe">

				<h3 class="Nome_detalhe"><?=$this->detalheProduto->getTitulo()?></h3>

				<!--  <strike class="precoAntigo_produto">R$ 7,50</strike>-->
				<p class="precoProduto_detalhe">
					<em class="un_monetaria">
					<strong><?=$this->detalheProduto->getValor(true)?></strong></em> 
				</p>
				<?
    								        if($this->detalheProduto->getEstoque()[0]->getQuantidade() == 1)
    								        {
    								            ?>
    								            <div class="smsEstoque" style="display:block;">Limite máximo de estoque!</div>
    								            <?
    								        }
    								        else
    								        {
    								        	?>
    								        	<div class="smsEstoque" style="display:none;"></div>
    								        	<?
    								        }
    								        ?>
                <?
                                    if($this->detalheProduto->getEstoque()[0]->getQuantidade() != 0)
                                    {
                                ?>
				<div class="qtd_produto">
					<p class="text_qtd">Quantidade</p>
					<input id="produto_<?=$this->detalheProduto->getIdproduto()?>" disabled class="box_qtd" type="text" name="quantidade" value="1" style="background-color:#fff">
					<ul class="produto_quantidade">
						<li class="qtd_mudar qtMais">
							<a href="#">mais</a>
						</li>
						<li class="qtd_mudar qtMenos">
							<a href="#">menos</a>
						</li>

					</ul>
				</div>
                                
				<div class="btn_detalhe">
					<button class="btn_carrinhoCompras_detalhe actionAddCarrinho" rev="<?=$this->detalheProduto->getIdproduto()?>" title="Adicionar ao carrinho de compras">Adicionar ao <br /> carrinho de compras</button>
					<!--<a href="<?=$this->url("publico-carrinho-compra")?>" rev="<?=$this->detalheProduto->getIdproduto()?>" class="btn_comprar_detalhe" title="Comprar">Comprar</a>-->
				</div>
                               <?php 
                      			    
                                    }
                                    else
                                    {
                                    	?>
                          <div class="qtd_produto">
							<p class="text_qtd">Quantidade</p>
							<input id="produto_<?=$this->detalheProduto->getIdproduto()?>" disabled class="box_qtd" type="text" name="quantidade" value="0">
					      <ul class="produto_quantidade">
							<li class="qtd_mudar qtMais">
								<a href="#">mais</a>
							</li>
							<li class="qtd_mudar qtMenos">
				 				<a href="#">menos</a>
							</li>
					      </ul>
				         </div>
				         
							<div class="btn_detalhe">
								<button class="btn_carrinhoCompras_detalhe_off">Produto indisponível</button><br/>
								<span class="txt_categoria_off" title="Avise-me quando chegar" style="margin-left:0px">Avise-me quando chegar</span>
							</div>          	
                                    	<?php 
                                   
                                    }
                      			?> 
			</div>
           
			
			<div class="informacoes_produtos">
				 <span class="mouse_imagem">passe o mouse na imagem</span>
				<h4 class="inf_produtos">Informações sobre o produto</h4>
				<p class="ingredientes">Detalhe:</p>
				<p class="ingredientes_inf"><?=$this->detalheProduto->getDescricao()?></p>
			</div>
<?php 
            if($this->nutricional)
            {
?>
                  <!--tabela Nutricional-->
				<table class="tabelaNutricional" summary="layout table">
					<thead>
						<tr>
						<th class="desc">Item</th>
						<th class="qtd">Quantidade por porção</th>
							<th class="vd">VD*</th>
						</tr>
					</thead>
					    <tbody>
							<tr>
							<th class="desc"></th>
							<td class="qtd">
							<?=$this->detalheProduto->getImformacaoNutricional();?>							
							</td>
							<td class="vd"></td>
							</tr>

							<?php 
							    foreach($this->nutricional AS $nutricional)
							    {
							?>

							<tr>
							<th class="desc"><?=$nutricional->getProdutonutricionalNomes()->getNome()?></th>
							<td class="qtd"><?=$nutricional->getQuantidade()?></td>
							<td class="vd"><?=$nutricional->getVd()?></td>
							</tr>
                        <?php 
							    }
                        ?>
							<tr>
							<th class="desc"></th>
							<td class="qtd">
							<?=$this->detalheProduto->getComplemento();?>
							</td>
							<td class="vd"></td>
							</tr>
						</tbody>
							<tfoot>
								<tr>
								<td colspan="3">
								<p class="obsTxt"></p>
								</td>
								</tr>
							</tfoot>
				    </table>
                  <!--Fim da Tabela Nutricional-->
                  <?php 
            }
                  ?>
    	</div>	
    </div>

    <!--box mais produtos-->
<?php 
		if(count($this->produtosRelacionados) > 0)
		{
?>
<div id="VejaTambem">

    <h2><span class="tt_top_list_right">Veja mais produtos</span></h2>	

    <div id="box_vejaTambem">
    <?php 
        foreach($this->produtosRelacionados AS $relacionados)
        {
    ?>

    	<div class="box_vejaTambem">
		    	<p class="desc_prod">
		    	    <a class="desc_prod" href="<?php echo $this->url('publico-categoria/publico-categoria-e-subcategoria/publico-produto', array('categoriaslug'=>$relacionados->getProdutosubcategoria()->getCategorias()->getSlug(), 'subcategoriaslugSub'=>$relacionados->getProdutosubcategoria()->getSlugSubcategoria(), 'produtoSlug'=>$relacionados->getSlugProduto() ));?>" title="<?=$relacionados->getTitulo();?>">
		    	        <?=$relacionados->getTitulo();?>
		    	    </a>
		    	</p>
		    	<div class="left_vejaTambem">
		    	 <a class="desc_prod" href="<?php echo $this->url('publico-categoria/publico-categoria-e-subcategoria/publico-produto', array('categoriaslug'=>$relacionados->getProdutosubcategoria()->getCategorias()->getSlug(), 'subcategoriaslugSub'=>$relacionados->getProdutosubcategoria()->getSlugSubcategoria(), 'produtoSlug'=>$relacionados->getSlugProduto() ));?>" title="<?=$relacionados->getTitulo();?>">
		    		<img src="<?=$this->basePath()?>/images/produtos/thumb_small/<?php echo $relacionados->getFoto();?>" alt="" title=""  class="maisProd" />
		    	    </a>
		    	</div>

		    	<div class="right_vejaTambem">
		    		    
						<p class="precoProduto_VejaTambem">
						    
							<em class="un_monetaria"><strong><?=$relacionados->getValor(true)?></strong></em> 
							
						</p>

						<div class="qtd_produto qtd_VejaTambem">
							
							<input  id="relacionadoProd_<?=$relacionados->getIdproduto()?>" class="box_qtd" type="text" name="quantidade1" value="1">
							<ul class="produto_quantidade">
								<li class="qtd_mudar qtMais">
									<a href="#">mais</a>
								</li>
								<li class="qtd_mudar qtMenos">
									<a href="#">menos</a>
								</li>

							</ul>
							<br/><span class="smsEstoque smsEstoqueVejaMais" style="display:none"></span>
						</div>
			   </div>
			   <button class="btn_carrinhoCompras_vejaTambem  actionAddCarrinho" rel="0" rev="<?=$relacionados->getIdproduto()?>" title="Adicionar ao carrinho de compras">Adicionar ao carrinho de compras</button>
			  <a href="<?=$this->url("publico-carrinho-compra")?>" rev="<?=$relacionados->getIdproduto()?>" class="btn_comprar_vejaTambem btn_comprar_detalhe" title="Comprar" style="margin-top:1px;">Comprar</a>
		</div>
<?php 
    
        }
?>

		
   </div>
</div>
<?php 
		}
?>
<script src='<?=$this->basePath()?>/js/elevatezoom/jquery.elevatezoom.js'></script>
<script type="text/javascript">

$(document).ready(function () {
	$("#zoom_03").elevateZoom({
		gallery:'gallery_01', 		
		galleryActiveClass: "active",
		cursor: 'pointer', 			
		loadingIcon: "spinner.gif"
	}); 

	$("#zoom_03").bind("click", function(e) {  
	  var ez =   $('#zoom_03').data('elevateZoom');
	  ez.closeAll(); //NEW: This function force hides the lens, tint and window	
		$.fancybox(ez.getGalleryList());
	  return false;
	});

}); 

</script>



