<?php
$formatUrl = function ($page){
	if(isset($_GET['pagina']))
	{
		if(isset($_GET['p']))
		{
			if(isset($_GET['ordenarPor']))
			{
				$url = "?pagina=$page&p={$_GET['p']}&ordenarPor={$_GET['ordenarPor']}";
			}
			else
			{
			    $url = "?pagina=$page&p={$_GET['p']}";
			}
		}
		elseif(isset($_GET['item']))
		{
		    if(isset($_GET['ordenarPor']))
		    {
		    	$url = "?pagina=$page&item={$_GET['item']}&ordenarPor={$_GET['ordenarPor']}";
		    }
		    else
		    {
		    	$url = "?pagina=$page&item={$_GET['item']}";
		    }
		}		
		else
		{
		    if(isset($_GET['ordenarPor']))
		    {
		    	$url = "?pagina=$page&ordenarPor={$_GET['ordenarPor']}";
		    }
		    else
		    {
		    	$url = "?pagina=$page";
		    }
		}
		return $url;
	}
	else
	{
	    if(isset($_GET['p']))
	    {
	    	if(isset($_GET['ordenarPor']))
	    	{
	    		$url = "?pagina=$page&p={$_GET['p']}&ordenarPor={$_GET['ordenarPor']}";
	    	}
	    	else
	    	{
	    		$url = "?pagina=$page&p={$_GET['p']}";
	    	}
	    }
	    elseif(isset($_GET['item']))
	    {
	    	if(isset($_GET['ordenarPor']))
	    	{
	    		$url = "?pagina=$page&item={$_GET['item']}&ordenarPor={$_GET['ordenarPor']}";
	    	}
	    	else
	    	{
	    		$url = "?pagina=$page&item={$_GET['item']}";
	    	}
	    }
	    else
	    {
	    	if(isset($_GET['ordenarPor']))
	    	{
	    		$url = "?pagina=$page&ordenarPor={$_GET['ordenarPor']}";
	    	}
	    	else
	    	{
	    		$url = "?pagina=$page";
	    	}
	    }
	    return $url;
	}
};
?>
<?php if ($this->pageCount): ?>
<ul class="box_paginacao" style="width: 190px !important;">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <li class="seta_paginacao">
        <a href="<?php echo $formatUrl($this->previous) ?>">
            <img class="st_esq" src="<?=$this->basePath()?>/images/seta_dir2_paginacao.png">
        </a>
    </li>
    <?php else: ?>
    <li class="seta_paginacao">
        <img class="st_esq" src="<?=$this->basePath()?>/images/seta_esq_paginacao.png">
    </li>
    <?php endif; ?>
    
    <li><span class="box_numeral_ligado"><?php  echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> produto(s)</span></li>
    
    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
    <li class="seta_paginacao">
        <a href="<?php echo $formatUrl($this->next) ?>">
            <img class="st_dir" src="<?=$this->basePath()?>/images/seta_dir_paginacao.png">
        </a>
    </li>
    <?php else: ?>
    <li class="seta_paginacao">
        <img class="st_dir" src="<?=$this->basePath()?>/images/seta_esq2_paginacao.png">
    </li>
    <?php endif; ?>
</ul>
<?php endif; ?>